{
 "title": "Device View",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DeviceTopic", "label": "Device", "query": "Motor1" }
  ]
 },
 "panels": [
  {
   "title": "Vibration Data",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_data\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Edge/MotorModel/vibration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Diagnosis History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/prediction\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fault_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Edge to Cloud Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/prediction\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"edge_to_cloud_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Vibration FFT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fft_vibration\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Vibration/fft\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Diagnosis",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/prediction\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"fault_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Compute Payload Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"payload_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"payload_size_mb\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Metrics/vibration_publisher/compute\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Storage Payload Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"payload_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"payload_size_mb\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Metrics/vibration_publisher/storage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}