{
 "title": "Overview",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Motor 1 Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_data\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor1/Edge/MotorModel/vibration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Diagnosis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor1/Analysis/Diagnosis/prediction\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"fault_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Edge to Cloud Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor1/Analysis/Diagnosis/prediction\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"edge_to_cloud_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor 2 Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_data\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor2/Edge/MotorModel/vibration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Diagnosis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor2/Analysis/Diagnosis/prediction\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"fault_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Edge to Cloud Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor2/Analysis/Diagnosis/prediction\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"edge_to_cloud_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor 3 Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vibration_data\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor3/Edge/MotorModel/vibration\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Diagnosis",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor3/Analysis/Diagnosis/prediction\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"fault_code\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Edge to Cloud Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"fault_diagnosis\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/Motor3/Analysis/Diagnosis/prediction\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"edge_to_cloud_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}