{
 "title": "Temperature Device View",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DeviceTopic", "label": "Device", "query": "Motor1" }
  ]
 },
 "panels": [
  {
   "title": "Temperature Data",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_data\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Edge/MotorModel/temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Alarm History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_alarm\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alarm\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Edge to Cloud Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_alarm\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"edge_to_cloud_latency_ms\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Max Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_alarm\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_temperature_c\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature_alarm\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Analysis/Diagnosis/temperature\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"alarm\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Storage Payload Size",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"FlexUNS_Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"payload_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"payload_size_mb\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"Enterprise/Site/Area/Line1/${DeviceTopic}/Metrics/temperature_publisher/storage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}